# Generated by Django 4.0.4 on 2022-05-27 20:15model

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symptoms', models.CharField(max_length=500)),
            ],
        ),
    ]
