# Generated by Django 4.0.4 on 2022-05-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
