# Generated by Django 4.0.4 on 2022-05-27 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_doctor_dob_alter_doctor_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 16, 31, 37, 108935)),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='date_of_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 16, 31, 37, 107933)),
        ),
    ]
