# Generated by Django 4.0.4 on 2022-05-27 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_doctor_dob_alter_hospital_date_of_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('p_email', models.EmailField(max_length=100, unique=True)),
                ('p_contact', models.BigIntegerField()),
                ('p_age', models.IntegerField()),
                ('d_name', models.CharField(max_length=100)),
                ('h_name', models.CharField(max_length=100)),
                ('s_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('fee', models.IntegerField()),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 14, 48, 4, 555104)),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='date_of_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 14, 48, 4, 554105)),
        ),
    ]
