# Generated by Django 4.0.4 on 2022-05-27 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_appointment_alter_doctor_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.CharField(default='nil', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 16, 47, 52, 237572)),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='date_of_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 16, 47, 52, 236566)),
        ),
    ]
