# Generated by Django 4.0.4 on 2022-05-27 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_appointment_p_gender_alter_doctor_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='p_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 23, 7, 42, 824548)),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='date_of_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 23, 7, 42, 823552)),
        ),
    ]
